// Mapa de iconos de lucide-react para materias.
// El campo `icon` en Subject guarda strings como "BookOpen", "Calculator", etc.
// Este archivo los resuelve a componentes reales.

import {
  BookOpen,
  Calculator,
  Globe,
  Leaf,
  FlaskConical,
  Atom,
  Map,
  Landmark,
  Dumbbell,
  Palette,
  Scale,
  Puzzle,
  Users,
  Cpu,
  Music,
  Camera,
  PenTool,
  Heart,
  Star,
  Wrench,
  BookText,
  Beaker,
  Languages,
  Megaphone,
  Laptop,
  Hammer,
  BookMarked,
  Microscope,
  Sigma,
  Pi,
  Trees,
  Mountain,
  Cloud,
  Scroll,
  Flag,
  Shield,
  Brush,
  Music2,
  Code,
  CodeXml,
  Terminal,
  Zap,
  Lightbulb,
  GraduationCap,
  Cross,
  Sun,
  Compass,
  TestTube,
  Telescope,
  Pencil,
  Ruler,
  Database,
  type LucideIcon,
} from "lucide-react";

export const ICON_MAP: Record<string, LucideIcon> = {
  BookOpen,
  Calculator,
  Globe,
  Leaf,
  FlaskConical,
  Atom,
  Map,
  Landmark,
  Dumbbell,
  Palette,
  Scale,
  Puzzle,
  Users,
  Cpu,
  Music,
  Camera,
  PenTool,
  Heart,
  Star,
  Wrench,
  BookText,
  Beaker,
  Languages,
  Megaphone,
  Laptop,
  Hammer,
  BookMarked,
  Microscope,
  Sigma,
  Pi,
  Trees,
  Mountain,
  Cloud,
  Scroll,
  Flag,
  Shield,
  Brush,
  Music2,
  Code,
  CodeXml,
  Terminal,
  Zap,
  Lightbulb,
  GraduationCap,
  Cross,
  Sun,
  Compass,
  TestTube,
  Telescope,
  Pencil,
  Ruler,
  Database,
};

export const ICON_OPTIONS = Object.keys(ICON_MAP);

export function getSubjectIcon(iconName?: string | null): LucideIcon {
  if (iconName && ICON_MAP[iconName]) return ICON_MAP[iconName];
  return BookOpen;
}

// Colores predefinidos para materias (mismos del migration script)
export const SUBJECT_COLORS = [
  { hex: "#3B82F6", label: "Azul" },
  { hex: "#8B5CF6", label: "Violeta" },
  { hex: "#06B6D4", label: "Cyan" },
  { hex: "#22C55E", label: "Verde" },
  { hex: "#10B981", label: "Esmeralda" },
  { hex: "#A855F7", label: "Púrpura" },
  { hex: "#F59E0B", label: "Ámbar" },
  { hex: "#EF4444", label: "Rojo" },
  { hex: "#DC2626", label: "Rojo oscuro" },
  { hex: "#B91C1C", label: "Carmesí" },
  { hex: "#F97316", label: "Naranja" },
  { hex: "#EC4899", label: "Rosa" },
  { hex: "#6366F1", label: "Índigo" },
  { hex: "#14B8A6", label: "Teal" },
  { hex: "#64748B", label: "Gris" },
  { hex: "#0EA5E9", label: "Sky" },
  { hex: "#F472B6", label: "Rosa claro" },
  { hex: "#C4B5FD", label: "Lavanda" },
  { hex: "#FB7185", label: "Coral" },
  { hex: "#FDBA74", label: "Durazno" },
  { hex: "#EAB308", label: "Amarillo" },
  { hex: "#FACC15", label: "Dorado" },
  { hex: "#D6D3D1", label: "Arena" },
  { hex: "#E9D5FF", label: "Lila" },
  { hex: "#1E40AF", label: "Azul marino" },
  { hex: "#1D4ED8", label: "Azul profundo" },
  { hex: "#6B21A8", label: "Púrpura oscuro" },
  { hex: "#475569", label: "Azul pizarra" },
  { hex: "#1F2937", label: "Carbón" },
  { hex: "#3730A3", label: "Índigo oscuro" },
  { hex: "#7C3AED", label: "Violeta medio" },
  { hex: "#0E7490", label: "Cian oscuro" },
  { hex: "#84CC16", label: "Oliva" },
  { hex: "#166534", label: "Verde bosque" },
  { hex: "#86EFAC", label: "Salvia" },
  { hex: "#65A30D", label: "Lima" },
  { hex: "#4D7C0F", label: "Musgo" },
  { hex: "#0F766E", label: "Turquesa oscuro" },
  { hex: "#334155", label: "Grafito" },
  { hex: "#92400E", label: "Bronce" },
];

export function hexToRgba(hex: string, alpha: number): string {
  const r = parseInt(hex.slice(1, 3), 16);
  const g = parseInt(hex.slice(3, 5), 16);
  const b = parseInt(hex.slice(5, 7), 16);
  return `rgba(${r}, ${g}, ${b}, ${alpha})`;
}
